set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'isRuslan/vim-es6'
Plugin 'rust-lang/rust.vim'
Plugin 'tomlion/vim-solidity'
call vundle#end()
filetype plugin indent on

syntax on
set number
set smartindent
set shiftwidth=2
set tabstop=2
set expandtab
set showmatch

